### ISSUE TITLE
Ajouter un bouton "?" d'information

### ISSUE THREAD

**Issue by Albanksy** [voteetvous/app#46]
# TODO
- [x] Ajouter une page Methodologie sur le site ( redaction seulement )
- [ ] Ajouter la modale d'informations ( technique )
- [x] Rédiger le contenu de la modale ( redaction seulement )

> Sur le design initial, il y avait un petit bouton "?" rond d'information pour accéder à des infos sur nous. Il faudrait l'ajouter sur la carte d'accueil pour qu'on écrive qui on est, avec un lien vers notre site et peut-être une page méthodologie par exemple ou un mail de contact.

**Comment by barodeur** [comment]
Oui,

Il faut préparer cette page "Méthodologie sur le site".

**Comment by barodeur** [comment]
@bkurc Est-ce que tu peux t'en occuper où trouver quelqu'un pour s'en occuper ?

**Comment by Albanksy** [comment]
La page est prête, tu peux intégrer le "?" ?

**Comment by Albanksy** [comment]
Texte pour le bouton d'information :
`10 des 11 candidats à l’élection présidentielle ont répondu à notre questionnaire. Plus d’information ici [lien].`
Et avant ça, chaque logo de bouton avec les mentions `D'accord` / `Pas d'accord`
